# Generated by Django 5.2.4 on 2025-07-16 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='A unique slug for the category URL.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Category Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Category Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product Name')),
                ('slug', models.SlugField(help_text='A unique slug for the product URL.', max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (GHS)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Available Stock')),
                ('available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('image', models.ImageField(blank=True, help_text='Upload a product image. If none, a placeholder will be used.', null=True, upload_to='products/', verbose_name='Product Image')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'), models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx')],
            },
        ),
    ]
