# Generated by Django 5.2.5 on 2026-07-22 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickCashOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('earning_range', models.CharField(blank=True, help_text='e.g. ₵80 – ₵650', max_length=100)),
                ('link', models.URLField(blank=True)),
                ('offer_type', models.CharField(choices=[('affiliate', 'Affiliate'), ('survey', 'Survey'), ('local', 'Local Gig')], default='affiliate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Blank means this is an official EarnAccra partner offer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earn_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('delivery', 'Delivery & Logistics'), ('tutoring', 'Education & Tutoring'), ('tech', 'Tech & Repairs'), ('other', 'Other Services')], default='other', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('contact_phone', models.CharField(help_text='WhatsApp / contact number shown to customers', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Snapshot of the service price at booking time', max_digits=10)),
                ('platform_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('provider_earning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_bookings_made', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='earn.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarningTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for earnings/credits, negative for withdrawals', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('SERVICE', 'Service Booking'), ('QUICK', 'Quick Cash'), ('MANUAL', 'Manually Logged'), ('WITHDRAWAL', 'Withdrawal')], default='MANUAL', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_transactions', to=settings.AUTH_USER_MODEL)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='earn.servicebooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
