# Generated by Django 5.2.5 on 2026-06-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(max_length=255, verbose_name='Shipping Full Name')),
                ('shipping_address_line1', models.CharField(max_length=255, verbose_name='Shipping Address Line 1')),
                ('shipping_address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line 2')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Shipping City')),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping State/Region')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Postal Code')),
                ('shipping_country', models.CharField(max_length=100, verbose_name='Shipping Country')),
                ('shipping_phone_number', models.CharField(max_length=20, verbose_name='Shipping Phone Number')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount (GHS)')),
                ('original_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original Total Before Discount')),
                ('coupon_applied', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coupon Code Applied')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Percentage')),
                ('payment_method', models.CharField(choices=[('paystack', 'Paystack Online Gateway'), ('flutterwave', 'Flutterwave Payment Link'), ('momo', 'Mobile Money Express Direct'), ('cod', 'Pay on Delivery / Cash')], default='paystack', max_length=20)),
                ('payment_status', models.BooleanField(default=False, verbose_name='Payment Verified')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Transaction ID Reference')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Global Order',
                'verbose_name_plural': 'Global Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name (Snapshot)')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Snapshot)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity Ordered')),
            ],
            options={
                'verbose_name': 'Line Order Item',
                'verbose_name_plural': 'Line Order Items',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Region')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(default='Ghana', max_length=100, verbose_name='Country')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('is_default', models.BooleanField(default=False, verbose_name='Set as Default')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending Fulfillment'), ('Processing', 'Processing / Packing'), ('Shipped', 'Handed over to Courier'), ('Delivered', 'Delivered Successfully'), ('Cancelled', 'Cancelled / Invalid'), ('Refunded', 'Returned & Funds Reversed')], default='Pending', max_length=50, verbose_name='Fulfillment Status')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Vendor Subtotal (GHS)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Vendor Shipping Fee')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Courier Air Waybill / Tracking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Sub-Order',
                'verbose_name_plural': 'Vendor Sub-Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
