# Generated by Django 5.2.5 on 2026-06-21 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Global Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Product Link'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shippingaddress', verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='parent_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.order', verbose_name='Parent Order Group'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='shops.shop', verbose_name='Vendor Shop'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sub_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.suborder', verbose_name='Vendor Sub-Order Group'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('user', 'full_name', 'address_line1', 'city', 'country')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_date'], name='orders_orde_order_d_35ab88_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='orders_orde_user_id_a87c6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
