# Generated by Django 5.2.4 on 2026-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_applied',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Coupon Code Applied'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Percentage'),
        ),
        migrations.AddField(
            model_name='order',
            name='original_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original Total Before Discount'),
        ),
    ]
