# Generated by Django 5.2.4 on 2026-05-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon_applied_order_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='pay_on_delivery', max_length=20),
        ),
    ]
