# Generated by Django 5.2.5 on 2026-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Fulfillment'), ('Processing', 'Processing / Packing'), ('Shipped', 'Handed over to Courier(Delivering)'), ('Delivered', 'Delivered Successfully'), ('Cancelled', 'Cancelled / Invalid'), ('Refunded', 'Returned & Funds Reversed')], default='Pending', max_length=50, verbose_name='Fulfillment Status'),
        ),
    ]
