# Generated by Django 5.2.5 on 2026-07-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Rate Limit Attempt',
                'verbose_name_plural': 'Rate Limit Attempts',
                'indexes': [models.Index(fields=['key', 'created_at'], name='core_rateli_key_07e3ec_idx')],
            },
        ),
    ]
