# apps/vendors/views.py

import requests
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from apps.products.models import Shop
from .forms import VendorOnboardingForm
from .decorators import vendor_required


@login_required
@vendor_required
def onboard_vendor_shop(request):
    """
    Handles live merchant subaccount instantiation via the Paystack API.
    Only accessible to admin-approved accounts.
    """
    # Defensive Check: Block users who have already linked their payout information
    existing_shop = Shop.objects.filter(user=request.user).first()
    if existing_shop and existing_shop.paystack_subaccount_code:
        messages.info(request, "Your merchant payout profile is already verified and active.")
        return redirect('vendors:dashboard')

    if request.method == 'POST':
        form = VendorOnboardingForm(request.POST)
        if form.is_valid():
            paystack_url = "https://api.paystack.co/subaccount"
            headers = {
                "Authorization": f"Bearer {settings.PAYSTACK_SECRET_KEY}",
                "Content-Type": "application/json"
            }
            
            payload = {
                "business_name": form.cleaned_data['business_name'],
                "settlement_bank": form.cleaned_data['settlement_bank'],
                "account_number": form.cleaned_data['account_number'],
                "percentage_charge": 5.0, # ⚡ Platform captures a 5% transaction commission
                "primary_contact_email": request.user.email
            }
            
            try:
                response = requests.post(paystack_url, json=payload, headers=headers, timeout=12)
                res_data = response.json()
                
                if response.status_code == 201 and res_data.get('status'):
                    # Extract the secure subaccount code generated by Paystack
                    subaccount_code = res_data['data']['subaccount_code']
                    
                    # Store or update the vendor's Shop profile model instance
                    shop, created = Shop.objects.get_or_create(user=request.user)
                    shop.name = form.cleaned_data['business_name']
                    shop.paystack_subaccount_code = subaccount_code
                    shop.save()
                    
                    messages.success(request, "Payout gateway activated! Your store can now receive customer payouts.")
                    return redirect('vendors:dashboard')
                else:
                    error_msg = res_data.get('message', 'Invalid banking credentials provided.')
                    messages.error(request, f"Paystack Activation Failed: {error_msg}")
                    
            except requests.RequestException:
                messages.error(request, "Gateway connection timeout. Payout validation failed.")
        else:
            messages.error(request, "Please resolve form issues before submitting.")
    else:
        form = VendorOnboardingForm()
        
    return render(request, 'vendors/onboard.html', {'form': form})