# Generated by Django 5.2.5 on 2026-06-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Shop Name')),
                ('slug', models.SlugField(blank=True, help_text='A unique slug for the shop URL.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Shop Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shops/', verbose_name='Shop Logo/Banner')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20, verbose_name='Approval Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Soft Deleted')),
                ('paystack_subaccount_code', models.CharField(blank=True, help_text="The merchant's unique Paystack Subaccount ID.", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['-created_at'],
            },
        ),
    ]
