# Generated by Django 5.2.5 on 2026-06-21 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Shop Owner'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['slug'], name='shops_shop_slug_f77e23_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_active', 'is_deleted', 'status'], name='shops_shop_is_acti_290446_idx'),
        ),
    ]
