# Generated by Django 5.2.5 on 2026-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone number to reach the vendor.', max_length=20, null=True, verbose_name='Contact Phone Number'),
        ),
    ]
