# Generated by Django 5.2.5 on 2026-06-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Leave blank for platform-wide coupons that apply across all items.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='shops.shop', verbose_name='Vendor Shop Scope'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'active'], name='promotions__code_de136d_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_to'], name='promotions__valid_f_65a77a_idx'),
        ),
    ]
